#import "./ResponseFragment.gql"
#import "./AssignmentFragment.gql"

mutation AddAssignment($assignment: NewAssignment!) {
  add(assignment: $assignment) {
    ...mutationResponse
    assignment {
      ...assignment
    }
  }
}
